import os

PICAMDIR = os.environ["PICAMDIR"]
PICAMSTATE = os.path.join(PICAMDIR, 'state')
PICAMHOOKS = os.path.join(PICAMDIR, 'hooks')
MESSAGERIEDIR = os.environ["MESSAGERIEDIR"]
ACCUEIL = os.environ["ACCUEIL"]

MEDIADIR = os.environ["MESSAGERIEMEDIADIR"]
PHOTOSDIR = os.path.join(MEDIADIR, 'photo')
ACTIONDIR = os.path.join(MEDIADIR, 'actions')
SLIDESHOWDIR = os.path.join(MEDIADIR, 'slideshow')

PLAYLISTID = os.environ["PLAYLISTID"]
CONFDIR = os.environ["MESSAGERIECONFDIR"]
SECRETFILE = os.environ["MESSAGERIESECRETFILE"]
OAUTH2FILE = os.environ["OAUTH2FILE"]

if os.environ["MESSAGERIEROTATION"] == 'oui':
  ROTATION = True
else:
  ROTATION = False

OAUTH2PATH = os.path.join(CONFDIR,OAUTH2FILE)
CLIENT_SECRETS_FILE = os.path.join(CONFDIR, SECRETFILE) 

CAMERA_MAX_X = 800
CAMERA_MAX_Y = 450
IDENTIFICATION_CAMERA_RATIO = 2.5
CAMERA_CAPTURE_X = 320 #int(CAMERA_MAX_X / IDENTIFICATION_CAMERA_RATIO)
CAMERA_CAPTURE_Y = 240 #192 #int(CAMERA_MAX_Y / IDENTIFICATION_CAMERA_RATIO)

def test():
  print(PICAMDIR)
  print(PICAMSTATE)
  print(PICAMHOOKS)
  print(MEDIADIR)
  print(PHOTOSDIR)
  print(PLAYLISTID)
  print(CONFDIR)
  print(SECRETFILE)
  print(OAUTH2FILE)
  print(OAUTH2PATH)
  print(CLIENT_SECRETS_FILE)
  print(CAMERA_MAX_X)
  print(CAMERA_MAX_Y)
  print(IDENTIFICATION_CAMERA_RATIO)
  print(CAMERA_CAPTURE_X)
  print(CAMERA_CAPTURE_Y)

if __name__ == '__main__':
  test()
