import os

PICAMDIR = os.environ["PICAMDIR"]
MEDIADIR = os.environ["MESSAGERIEMEDIADIR"]
PLAYLISTID = os.environ["PLAYLISTID"]
CONFDIR = os.environ["MESSAGERIECONFDIR"]
SECRETFILE = os.environ["MESSAGERIESECRETFILE"]
OAUTH2FILE = os.environ["OAUTH2FILE"]

OAUTH2PATH = os.path.join(CONFDIR,OAUTH2FILE)
CLIENT_SECRETS_FILE = os.path.join(CONFDIR, SECRETFILE) 

